book.json

CF: Link to primer PDF in plugin configuration add

---

book.json

Reverts DynamoDS/DynamoPrimer#27

Revert "CF: Link to primer PDF in plugin configuration add"

---

book.json

CF: Added GA back into book.json

---

Appendix/A-3_packages.md

updates some links to mantis shrimp site and added arch-lab package.

added archi-lab package to list of packages

---

.htaccess.txt

Since .htaccess files could not be submitted directly. Add instructions here how to resolve domain-wise redirect and excluding ja and de subfolder.
@Racel

domain-wise redirect

---

de/.gitignore
ja/.gitignore

Add git ignore files to de and ja sub folders

Add gitignore files

---

en/README.md

Stable version change to 1.2.0
FYI: @Racel

Stable version

---

en/.htaccess.txt

Reverts DynamoDS/DynamoPrimer#72

Revert "additional updates"

---

en/12_Best-Practice/12-2_Graph-Strategies.md

Made minor typo changes to the primer

Small typo fixes

---

en/12_Best-Practice/12-3_Scripting-Reference.md

added a section on unmanaged code and some code samples.
@Racel

some additions to scripting references

---

en/08_Dynamo-for-Revit/8-1_The-Revit-Connection.md

Added Revit version compatibility table

Add revit versions

---

en/README.md

Add 1.3 PDF Download

---

en/book.json
en/styles/website.css

http -> https

---

de/10_Custom-Nodes/10-4_Python.md
de/Appendix/A-1_resources.md
en/10_Custom-Nodes/10-4_Python.md
en/Appendix/A-1_resources.md
ja/10_Custom-Nodes/10-4_Python.md
ja/Appendix/A-1_resources.md
zh-tw/10_Custom-Nodes/10-4_Python.md
zh-tw/Appendix/A-1_resources.md

Update all Designscript language guide links on content and appendix. DO NOT MERGE until 
learn page on DynamoBIM has been updated.
FYI:
@scottmitchell @mjkkirschner @Racel

Update language guide link

---

en/08_Dynamo-for-Revit/8-1_The-Revit-Connection.md

Amended Dynamo version and relevant links to dynamo 2.0.3 for revit 2017 to 2019.

Dynamo Version and Link amended to 2.0.3

---

DockerUtilities/DockerCommands.ps1
DockerUtilities/PreBuildScript.ps1

Add compress pdf file with ghost script.
Update image from 1.0.2 to 1.0.3.

Jenkinsfile

---

pipeline.yml

Changes to avoid Code Analysis

Changes to avoid Code Analysis

---

pipeline.yml

Changes to avoid Code Analysis

Changes to avoid Code Analysis Execution

---

DockerUtilities/BuildScript.ps1
DockerUtilities/DeployScript.ps1
DockerUtilities/DockerCommands.ps1
DockerUtilities/DockerDeployCommands.ps1
DockerUtilities/DockerPDFCompCommands.ps1
DockerUtilities/PostBuildScript.ps1
pipeline.yml

New feature is added to support a several languajes at the same time
https://jira.autodesk.com/browse/DYN-2395
- [ - ] PR title reflects the changes it introduces. Consider using this template: QNTM-XXXX: Implement X Feature
- [ - ] Code compiles correctly
- [ - ] No linting errors

Add language parameters.

---

cs/book.json
de/book.json
en/book.json
es/book.json
fr/book.json
it/book.json
ja/book.json
ko/book.json
pl/book.json
pt-br/book.json
ru/book.json
zh-cn/book.json
zh-tw/book.json

Add hyper links under language switch under English version
@RangerShen

Add en hyper links

---

fr/README.md

This is a Cherry-pick PR.
FYI: @RangerShen

Fix translation

---

pipeline.yml

Increase Timeout

---

DockerUtilities/BuildScript.ps1
DockerUtilities/DeployScript.ps1
DockerUtilities/DockerCommands.ps1
DockerUtilities/DockerDeployCommands.ps1
DockerUtilities/DockerPDFCompCommands.ps1
DockerUtilities/DockerVaultCommands.ps1
DockerUtilities/PostBuildScript.ps1
DockerUtilities/PostDeployScript.ps1
DockerUtilities/PreBuildScript.ps1
pipeline.yml

Test first version with PS7 scripst for the Jenkins pipeline

Staging branch new ps 7

---

pipeline.yml

Fix Issue about indentation in the file pipeline.yml, specifically in the white source scanning section (the job DynamoPrimer is failing in the White Source scanning section due to this indentation issue).
Check these if you believe they are true
@QilongTang 
@alfredo-pozo 
@mjkkirschner

Fix Identation

---

DockerUtilities/CopyLibrariesToHostScript.ps1
pipeline.yml

DynamoPrimer job for master branch run successfully in master-5 and was uploaded to White Source website, then the same code will be merged in **Staging-branch** 
Enable White Source scanning for third party libraries used in the DynamoPrimer repository
https://jira.autodesk.com/browse/DYN-2773
****
Check these if you believe they are true
@QilongTang 
@alfredo-pozo

DYN-27773 - Enable WhiteSource Scanning DynamoPrimer repo (Staging-branch)

---

DockerUtilities/BuildScript.ps1
DockerUtilities/CopyLibrariesToHostScript.ps1
DockerUtilities/DeployScript.ps1
DockerUtilities/DockerCommands.ps1
DockerUtilities/DockerDeployCommands.ps1
DockerUtilities/DockerPDFCompCommands.ps1
DockerUtilities/DockerVaultCommands.ps1
DockerUtilities/PostBuildScript.ps1
DockerUtilities/PostDeployScript.ps1
DockerUtilities/PreBuildScript.ps1
DockerUtilities/RestartDockerDesktop.ps1
DockerUtilities/SetupHost.ps1
pipeline.yml

Changes to Vault and exception management on CI/CD pipeline
This changes were **already merged** (Alfredo's pull request https://github.com/DynamoDS/DynamoPrimer/pull/224) to the master branch then we need to merge the same changes to the **Staging-branch.**
****
Check these if you believe they are true
@QilongTang 
@alfredo-pozo

Changes to Vault and exception management on CI/CD pipeline (Staging)

---

pipeline.yml

Define the DynamoPrimer (Staging-branch) schedule for triggering the job every month
****
Check these if you believe they are true
@QilongTang 
@alfredo-pozo

DYN-2960 - Enable monthly pipeline executions for repos with WS (Staging-branch)

---

pl/book.json

Update Pdf link for Polish lan

Update Pdf link

---

cs/book.json
de/book.json
en/book.json
es/book.json
fr/book.json
it/book.json
ja/book.json
ko/book.json
pl/book.json
pt-br/book.json
ru/book.json
zh-cn/book.json
zh-tw/book.json

* Update gitbook version
* Updater other languages
FYI: @zeusongit

Update gitbook version (#235)

---

cs/book.json
de/book.json
en/book.json
es/book.json
fr/book.json
it/book.json
ja/book.json
ko/book.json
pl/book.json
pt-br/book.json
ru/book.json
zh-cn/book.json
zh-tw/book.json

Reverts DynamoDS/DynamoPrimer#246

Revert "Update gitbook version (#235)"

---

pipeline.yml

Reverts DynamoDS/DynamoPrimer#237

Revert "Update of CI/CD pipeline to use Docker image with Node 10"

---

scripts/DockerCommands.ps1
scripts/PreBuildScript.ps1

@QilongTang Can you please protect the base branch?

Update Docker build image path

---

en/08_Dynamo-for-Revit/8-1_The-Revit-Connection.md

Revise the latest version supported for Revit 2019 to Dynamo 2.0.4

Version Update

---

pipeline.yml

removed code_analysis since we were skipping it anyway

switch to harmony

---

Jenkinsfile
pipeline.yml

- Changing node to use label "DynamoGPUWin".
- Adding step in Jenkinsfile to print all environment variables after build.

Change job to use node labels

---

pipeline.yml

Migrating staging branch to harmony

Moving Staging branch to harmony

---

scripts/DockerCommands.ps1
scripts/DockerDeployCommands.ps1
scripts/DockerPDFCompCommands.ps1

Evaluating ENVIRONMENT_LANGUAGE variable to exclude other languages if the pipeline run for an specific language.

Adding evaluation of Language variable

---

scripts/DockerCommands.ps1
scripts/DockerDeployCommands.ps1
scripts/DockerPDFCompCommands.ps1

Evaluating ENVIRONMENT_LANGUAGE variable to exclude other languages if the pipeline run for an specific language.
Fix the error in the previous PR

Updating DynamoPrimer scripts

---

scripts/DockerDeployCommands.ps1

Fixing the path of the legacy pdf file

Fix Uploading legacy DynamoPrimer1_3 pdf

---

scripts/DockerDeployCommands.ps1

Fixing the path of where is located DynamoPrimer1_3.pdf file and moving the code into if statement for "en" language, since this pdf was located in en folder only

Fix path for Uploading legacy DynamoPrimer1_3 pdf

---

fr/06_Designing-with-Lists/6-1_whats-a-list.md
fr/08_Dynamo-for-Revit/8-2_Selecting.md
fr/10_Custom-Nodes/10-1_Introduction.md

Hi @QilongTang , could you please merge this PR to master, there are some translation need to be updated, thank you.

Fix FRA translation

---

en/02_Hello-Dynamo/2-2_the_dynamo_ui.md

Correct Typo suggested by customer

Correct Typo

---

pipeline.yml

Update build machine label

---

scripts/DockerCommands.ps1

PR created for enable debug on gitbook build step because DynamoPrimer pipeline is failing and we need more error messages to identify the issue.

DYN-3916 Enable debug
